#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"

#define DOESNT_EXIST 0x420

#define SAFE_INIT(port, thingy) \
	if (port != DOESNT_EXIST) { \
		thingy \
	}

#define COMPETITION_BOT true

#define ENCODER_TICKS_PER_REV 360.0

// Tote Lifter

#define TOTE_LIFTER_LEFT_PORT 1
#define TOTE_LIFTER_RIGHT_PORT 2	//now same as practice bot whoohoo
#define TOTE_LIFTER_ENCODER_PORTS 0,1
#define TOTE_LIFTER_CRAAAW_INPUT_PORT 0
#define TOTE_LIFTER_ELEVATOR_INPUT_PORT 1

#define TOTE_LIFTER_PID_P 0.560
#define TOTE_LIFTER_PID_I 0.001
#define TOTE_LIFTER_PID_D 0.500

#define TOTE_LIFTER_40_HEIGHT 40
#define TOTE_LIFTER_30_HEIGHT 30
#define TOTE_LIFTER_20_HEIGHT 20
#define TOTE_LIFTER_FLOOR_HEIGHT 0

#define TOTE_LIFTER_MAX_DISTANCE 1850
#define TOTE_LIFTER_TOLERANCE 15

#define TOTE_LIFTER_TICKS_PER_INCH 64
#define TOTE_LIFTER_TICKS_PER_REV 1024
#define TOTE_LIFTER_TIMEOUT 5.0 // seconds

#define TOTE_LIFTER_ENCODER_CLOSE_TO_ZERO 5
#define TOTE_LIFTER_COUNT_ZEROED 50
#define TOTE_LIFTER_ZERO_SPEED .2
#define TOTE_LIFTER_ZERO_SPEED_MAG 0.8
#define TOTE_LIFTER_MAG_SENSOR_POSITION TOTE_LIFTER_TWO_TOTE

// OI
#define JOYSTICK_DRIVE_DEADBAND (0.05)
#define JOYSTICK_ROT_DEADBAND (0.15)
#define JOYSTICK_DEGREES_PER_TICK 5.0

// Stallable Motor
#define STALLABLE_ENC_MOVE_THRESHOLD 5
#define STALLABLE_POT_MOVE_THRESHOLD 0.3
#define STALLABLE_TIME_STOP 250

#endif
